### PR TITLE
Add a sample of gestures

### PR DESCRIPTION
**Pull request by asynchaizer**
Add a sample for the presentation of gestures that are added here -> https://github.com/KoalaPlot/koalaplot-core/pull/90
Additionally add and configure a project to run on iOS

### CODE REVIEW

**Comment by asynchaizer** [comment]
@gsteckman I see an [error](https://github.com/KoalaPlot/koalaplot-samples/actions/runs/11427966579/job/31858290819#step:5:58), but I don't understand what is the matter, because I don't have such a problem when running the task "kotlinNpmInstall" on a local machine.
Can you tell me what the problem might be and if any action is required on my part? 🤔

**Comment by gsteckman** [comment]
The problem is with the github action to do the check. It's not checking out and building koalaplot-core first. My 2 minute attempt to fix it didn't work, so I'll need to take a deeper look at it.

**Comment by gsteckman** [comment]
I fixed the check in main. Can you pull that into your branch and try again?

**Comment by asynchaizer** [comment]
> I fixed the check in main. Can you pull that into your branch and try again?

Done

**Pull request merged**
